#!/bin/bash

STAGE=$1
if [ -z "$1" ]; then
    STAGE=dev
fi

docker kill follow.markets
docker run -d --rm --name follow.markets \
  -p 6868:6868 \
  -v $(pwd)/configs/deploy.configs.json:/configs/configs.json \
  phat/follow.markets:${STAGE}
