#!/bin/bash

STAGE=$1
if [ -z "$1" ]; then
    STAGE=dev
fi

docker kill follow.market
docker run -d --rm --name follow.market \
  -p 6868:6868 \
  -v $(pwd)/configs/dev_configs.json:/configs/configs.json \
  phat/follow.market:${STAGE}
